// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPuuLJFiiEmCLTMb6B1SIeRV5MORmWIOs',
    appId: '1:919767452177:web:55da3a48a8016950f1ffb0',
    messagingSenderId: '919767452177',
    projectId: 'aissam-store-v2',
    authDomain: 'aissam-store-v2.firebaseapp.com',
    storageBucket: 'aissam-store-v2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRM6iWpxNuiuoaIDTDSJJGnrTpK8b3-wo',
    appId: '1:919767452177:android:cf4a328f0c11f26bf1ffb0',
    messagingSenderId: '919767452177',
    projectId: 'aissam-store-v2',
    storageBucket: 'aissam-store-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP21CiRBoFPs0_CSXF94RQKAvJCeLmkbo',
    appId: '1:919767452177:ios:939a4f235f876cd7f1ffb0',
    messagingSenderId: '919767452177',
    projectId: 'aissam-store-v2',
    storageBucket: 'aissam-store-v2.appspot.com',
    androidClientId: '919767452177-vpitk2c1riquvmn0rgc6osk9tv2g1tnj.apps.googleusercontent.com',
    iosClientId: '919767452177-b09eq0ngq1gaour1smvd4g50bihn5hk9.apps.googleusercontent.com',
    iosBundleId: 'com.example.aissamStoreV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP21CiRBoFPs0_CSXF94RQKAvJCeLmkbo',
    appId: '1:919767452177:ios:939a4f235f876cd7f1ffb0',
    messagingSenderId: '919767452177',
    projectId: 'aissam-store-v2',
    storageBucket: 'aissam-store-v2.appspot.com',
    androidClientId: '919767452177-vpitk2c1riquvmn0rgc6osk9tv2g1tnj.apps.googleusercontent.com',
    iosClientId: '919767452177-b09eq0ngq1gaour1smvd4g50bihn5hk9.apps.googleusercontent.com',
    iosBundleId: 'com.example.aissamStoreV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPuuLJFiiEmCLTMb6B1SIeRV5MORmWIOs',
    appId: '1:919767452177:web:c51b94c8beb95fb5f1ffb0',
    messagingSenderId: '919767452177',
    projectId: 'aissam-store-v2',
    authDomain: 'aissam-store-v2.firebaseapp.com',
    storageBucket: 'aissam-store-v2.appspot.com',
  );

}